[project]
name = "summative"
version = "0.1.0"
description = "Predicting Adult Mortality Rate in African Nations - Linear Regression Assignment"
requires-python = ">=3.10"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "joblib",
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-multipart",
    "jupyter",
    "ipykernel",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
